In [ ]:
!pip install yahoofinancials

In [2]:
import pandas as pd
from yahoofinancials import YahooFinancials
import datetime

In [4]:
ticker= 'ADBE'
yahoo_financials = YahooFinancials(ticker)
data = yahoo_financials.get_historical_price_data('2021-04-01','2021-04-30','daily')
data

{'ADBE': {'eventsData': {},
  'firstTradeDate': {'formatted_date': '1986-08-13', 'date': 524323800},
  'currency': 'USD',
  'instrumentType': 'EQUITY',
  'timeZone': {'gmtOffset': -14400},
  'prices': [{'date': 1617283800,
    'high': 487.0400085449219,
    'low': 480.7099914550781,
    'open': 483.1199951171875,
    'close': 483.3399963378906,
    'volume': 2664700,
    'adjclose': 483.3399963378906,
    'formatted_date': '2021-04-01'},
   {'date': 1617629400,
    'high': 495.510009765625,
    'low': 480.5,
    'open': 483.69000244140625,
    'close': 491.6199951171875,
    'volume': 2982500,
    'adjclose': 491.6199951171875,
    'formatted_date': '2021-04-05'},
   {'date': 1617715800,
    'high': 495.5899963378906,
    'low': 487.57000732421875,
    'open': 492.32000732421875,
    'close': 491.3399963378906,
    'volume': 1878300,
    'adjclose': 491.3399963378906,
    'formatted_date': '2021-04-06'},
   {'date': 1617802200,
    'high': 494.8500061035156,
    'low': 487.8900146484375,
    'open': 492.9800109863281,
    'close': 493.4100036621094,
    'volume': 1576800,
    'adjclose': 493.4100036621094,
    'formatted_date': '2021-04-07'},
   {'date': 1617888600,
    'high': 504.6000061035156,
    'low': 498.1400146484375,
    'open': 500.1600036621094,
    'close': 499.8399963378906,
    'volume': 2026000,
    'adjclose': 499.8399963378906,
    'formatted_date': '2021-04-08'},
   {'date': 1617975000,
    'high': 504.44000244140625,
    'low': 492.6000061035156,
    'open': 498.3699951171875,
    'close': 504.0400085449219,
    'volume': 1886900,
    'adjclose': 504.0400085449219,
    'formatted_date': '2021-04-09'},
   {'date': 1618234200,
    'high': 506.94000244140625,
    'low': 498.44000244140625,
    'open': 499.2900085449219,
    'close': 506.0299987792969,
    'volume': 1584600,
    'adjclose': 506.0299987792969,
    'formatted_date': '2021-04-12'},
   {'date': 1618320600,
    'high': 517.260009765625,
    'low': 506.7799987792969,
    'open': 506.8500061035156,
    'close': 514.8599853515625,
    'volume': 2195400,
    'adjclose': 514.8599853515625,
    'formatted_date': '2021-04-13'},
   {'date': 1618407000,
    'high': 517.780029296875,
    'low': 509.1300048828125,
    'open': 514.0,
    'close': 510.6300048828125,
    'volume': 1956400,
    'adjclose': 510.6300048828125,
    'formatted_date': '2021-04-14'},
   {'date': 1618493400,
    'high': 524.5900268554688,
    'low': 515.0999755859375,
    'open': 515.6699829101562,
    'close': 523.25,
    'volume': 2122300,
    'adjclose': 523.25,
    'formatted_date': '2021-04-15'},
   {'date': 1618579800,
    'high': 525.4400024414062,
    'low': 518.5499877929688,
    'open': 524.2100219726562,
    'close': 525.0800170898438,
    'volume': 2031600,
    'adjclose': 525.0800170898438,
    'formatted_date': '2021-04-16'},
   {'date': 1618839000,
    'high': 524.0,
    'low': 514.4400024414062,
    'open': 523.1300048828125,
    'close': 516.1699829101562,
    'volume': 1917700,
    'adjclose': 516.1699829101562,
    'formatted_date': '2021-04-19'},
   {'date': 1618925400,
    'high': 517.2899780273438,
    'low': 510.6000061035156,
    'open': 515.2899780273438,
    'close': 514.2100219726562,
    'volume': 1677500,
    'adjclose': 514.2100219726562,
    'formatted_date': '2021-04-20'},
   {'date': 1619011800,
    'high': 515.47998046875,
    'low': 509.54998779296875,
    'open': 515.02001953125,
    'close': 512.3400268554688,
    'volume': 1678100,
    'adjclose': 512.3400268554688,
    'formatted_date': '2021-04-21'},
   {'date': 1619098200,
    'high': 512.77001953125,
    'low': 504.05999755859375,
    'open': 508.0799865722656,
    'close': 507.2900085449219,
    'volume': 2084600,
    'adjclose': 507.2900085449219,
    'formatted_date': '2021-04-22'},
   {'date': 1619184600,
    'high': 517.5,
    'low': 508.3999938964844,
    'open': 508.7900085449219,
    'close': 515.8400268554688,
    'volume': 2257500,
    'adjclose': 515.8400268554688,
    'formatted_date': '2021-04-23'},
   {'date': 1619443800,
    'high': 516.3099975585938,
    'low': 510.25,
    'open': 513.5700073242188,
    'close': 515.7000122070312,
    'volume': 1387500,
    'adjclose': 515.7000122070312,
    'formatted_date': '2021-04-26'},
   {'date': 1619530200,
    'high': 519.1599731445312,
    'low': 511.3500061035156,
    'open': 518.0,
    'close': 517.3200073242188,
    'volume': 1944000,
    'adjclose': 517.3200073242188,
    'formatted_date': '2021-04-27'},
   {'date': 1619616600,
    'high': 519.1300048828125,
    'low': 510.0199890136719,
    'open': 515.239990234375,
    'close': 515.47998046875,
    'volume': 1472200,
    'adjclose': 515.47998046875,
    'formatted_date': '2021-04-28'},
   {'date': 1619703000,
    'high': 520.4500122070312,
    'low': 510.6199951171875,
    'open': 518.1099853515625,
    'close': 516.0900268554688,
    'volume': 1592500,
    'adjclose': 516.0900268554688,
    'formatted_date': '2021-04-29'}]}}

In [5]:
stocks = ['ADBE','FB','RELIANCE.NS','GOOG','SBIN.NS','9988.HK','BRK-A']

df = pd.DataFrame()
end = (datetime.date.today()).strftime('%Y-%m-%d')
start = (datetime.date.today()-datetime.timedelta(1825)).strftime('%Y-%m-%d')
for stock in stocks:
    yahoo_financials = YahooFinancials(stock)
    obj = yahoo_financials.get_historical_price_data(start,end,'daily')
    ohlv = obj[stock]['prices']
    temp = pd.DataFrame(ohlv)[['formatted_date','adjclose']]
    temp.set_index('formatted_date',inplace=True)
    temp.dropna(inplace=True)
    df[stock] = temp['adjclose']

In [6]:
df.shape

(1257, 7)

In [11]:
df.head()

,ADBE,FB,RELIANCE.NS,GOOG,SBIN.NS,9988.HK,BRK-A
formatted_date,,,,,,,
2016-10-19,108.389999,130.110001,524.781067,801.500000,250.795517,NaN,217350.0
2016-10-20,109.029999,130.000000,524.877625,796.969971,255.508972,NaN,216975.0
2016-10-21,109.029999,132.070007,513.608337,799.369995,253.839630,NaN,215600.0
2016-10-24,110.809998,133.279999,513.174011,813.109985,258.209412,NaN,215500.0
2016-10-25,109.029999,132.289993,511.991577,807.669983,256.736450,NaN,215250.0